require:
  # - rubocop-jekyll
  - rubocop-md
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

# inherit_gem:
#  rubocop-jekyll: .rubocop.yml

AllCops:
  Exclude:
    - binstub/**/*
    - vendor/**/*
    - demo/_site/*
    - Gemfile*
    - jekyll_archive_display.gemspec
  NewCops: enable

Gemspec/RequireMFA:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/BlockAlignment:
  Enabled: false

Layout/HashAlignment:
  EnforcedColonStyle: table
  Exclude:
    - jekyll_archive_display.gemspec

Layout/LineLength:
  Max: 150

Layout/MultilineMethodCallIndentation:
  Enabled: false

Lint/RedundantCopDisableDirective:
  Exclude:
    - jekyll_archive_display.gemspec

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - jekyll_archive_display.gemspec
    - spec/**/*

Metrics/MethodLength:
  Max: 25

Naming/FileName:
  Exclude:
    - Rakefile

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 15

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringConcatenation:
  Exclude:
    - spec/**/*

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
